# إزالة هذا السطر
version: '3.8' 

services: 
  postgres: 
    image: postgres:15-alpine 
    container_name: smart_attendance_db 
    environment: 
      POSTGRES_DB: smart_attendance_dev 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: password 
      PGDATA: /var/lib/postgresql/data/pgdata 
    ports: 
      - "5433:5432"  # تغيير المنفذ الخارجي من 5432 إلى 5433
    volumes: 
      - postgres_data:/var/lib/postgresql/data 
    networks: 
      - smart_attendance_network 

  redis: 
    image: redis:7-alpine 
    container_name: smart_attendance_redis 
    ports: 
      - "6380:6379"  # تغيير المنفذ الخارجي من 6379 إلى 6380
    volumes: 
      - redis_data:/data 
    networks: 
      - smart_attendance_network 

  adminer: 
    image: adminer:4.8.1  # تحديد إصدار بدلاً من latest
    container_name: smart_attendance_adminer 
    ports: 
      - "8080:8080" 
    depends_on: 
      - postgres 
    networks: 
      - smart_attendance_network 

volumes: 
  postgres_data: 
  redis_data: 

networks: 
  smart_attendance_network: 
    driver: bridge
# باقي الملف
